### ISSUE TITLE
connect ENOENT \\.\pipe\errorReporter

### ISSUE THREAD

**Issue by hyunho4532** [rogaha/docker-desktop#56]
I installed Docker Desktop and ran it,
but encountered an error similar to the one in the title

**Comment by thaJeztah** [comment]
:wave: @hyunho4532 I suspect you opened this ticket in the wrong repository / issue tracker. This issue tracker is for a project that was named "Docker Desktop", but before "Docker" created [Docker Desktop](https://docs.docker.com/desktop/).

From the description of your ticket (`connect ENOENT \\.\pipe\errorReporter`), I suspect you are using Docker's Docker Desktop for Windows; the correct issue tracker for that is https://github.com/docker/for-win/issues

Could you open a ticket there instead (if possible with additional information as requested in the issue-template on that repository).
