### ISSUE TITLE
Documentation not complete

### ISSUE THREAD

**Issue by onekilo79** [rogaha/docker-desktop#6]
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/usr/lib/xpra/xpra/xposix/gui.py:15: GtkWarning: IA__gdk_display_get_name: assertion `GDK_IS_DISPLAY (display)' failed
  _display = gtk.gdk.get_display()
Traceback (most recent call last):
  File "/usr/bin/xpra", line 7, in <module>
    xpra.scripts.main.main(__file__, sys.argv)
  File "/usr/lib/xpra/xpra/scripts/main.py", line 232, in main
    run_client(parser, options, args, mode)
  File "/usr/lib/xpra/xpra/scripts/main.py", line 367, in run_client
    from xpra.client import XpraClient
  File "/usr/lib/xpra/xpra/client.py", line 25, in <module>
    from xpra.platform.gui import ClientExtras
  File "/usr/lib/xpra/xpra/platform/gui.py", line 16, in <module>
    from xpra.xposix.gui import *
  File "/usr/lib/xpra/xpra/xposix/gui.py", line 16, in <module>
    assert _display, "cannot open the display with GTK, is DISPLAY set?"
AssertionError: cannot open the display with GTK, is DISPLAY set?

On the node I run 
python -c "import pygtk;pygtk.require('2.0');\
import gtk;print(gtk.gdk.get_display())"

And I get the following.  

(process:296): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
-c:1: GtkWarning: IA__gdk_display_get_name: assertion `GDK_IS_DISPLAY (display)' failed

Any ideas what additional setup is required to get this to work?

**Comment by Prathibha-mv** [comment]
Hi

Im trying to access remote desktop using xpra on windows.It works fine .But the Xpra display disappears when I do a commit to my running container which is causing a problem.Can you please suggest a solution to this error.
